=== ligengwasd/LigengRepository/OfbizForDB/framework/base/dtd/widget-grid.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="grids">
	    <xs:complexType>
	        <xs:sequence>
	            <xs:element maxOccurs="unbounded" ref="kd-grid"/>
	        </xs:sequence>
	    </xs:complexType>
	</xs:element>
	<!-- kd-grid start by ligeng-->
	<xs:element name="kd-grid">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="1" minOccurs="1" ref="kd-grid-columns"></xs:element>
				<xs:element maxOccurs="1" minOccurs="0" ref="kd-grid-toolbar"></xs:element>
				<xs:element maxOccurs="1" minOccurs="1" ref="kd-grid-datasource"></xs:element>
			</xs:sequence>
			<xs:attributeGroup ref="attlist.kd-grid"></xs:attributeGroup>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="attlist.kd-grid">
		<xs:attribute name="name" type="xs:string"></xs:attribute>
		<xs:attribute name="selectable" default="multiple, row">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="true"></xs:enumeration>
					<xs:enumeration value="false"></xs:enumeration>
					<xs:enumeration value="multiple, row"></xs:enumeration>
					<xs:enumeration value="cell"></xs:enumeration>
					<xs:enumeration value="row"></xs:enumeration>
					<xs:enumeration value="multiple, cell"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="editable" default="inline">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="inline"/>
					<xs:enumeration value="popup"/>
					<xs:enumeration value="incell"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="height" type="xs:integer"/>
		<xs:attribute name="sortableMode"  default="single">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="single"/>
					<xs:enumeration value="multiple"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="filterable" type="xs:boolean"></xs:attribute>
		<xs:attribute name="groupable" type="xs:boolean"></xs:attribute>
		<xs:attribute name="resizable" type="xs:boolean"></xs:attribute>
		<xs:attribute name="pageSizesInput" type="xs:boolean"></xs:attribute>
		<xs:attribute name="refresh" type="xs:boolean"></xs:attribute>
		<xs:attribute name="pageSizes" type="xs:boolean"></xs:attribute>
	</xs:attributeGroup>
<!-- kd-grid-datasource start by ligeng-->
	<xs:element name="kd-grid-datasource">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="1" ref="kd-grid-field"></xs:element>
			</xs:sequence>
			<xs:attributeGroup ref="attlist.kd-grid-datasource"></xs:attributeGroup>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="attlist.kd-grid-datasource">
		<xs:attribute name="gridName" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="entityName" type="xs:string" use="required"/>
		<xs:attribute name="modelId" use="required"/>
		<xs:attribute name="pageSize" use="optional"/>
		<xs:attribute name="read" type="xs:string" />
		<xs:attribute name="create" type="xs:string"/>
		<xs:attribute name="update" type="xs:string"/>
		<xs:attribute name="destroy" type="xs:string"/>
	</xs:attributeGroup>
	<!-- kd-grid-columns start by ligeng-->
	<xs:element name="kd-grid-columns">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="1" ref="kd-grid-column"></xs:element>
				<xs:element maxOccurs="unbounded" minOccurs="0" ref="kd-grid-command"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- kd-grid-toolbar start by ligeng-->
	<xs:element name="kd-grid-toolbar">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" ref="kd-grid-toolbar-sub"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- kd-grid-toolbar-sub start by ligeng-->
	<xs:element name="kd-grid-toolbar-sub">
		<xs:complexType>
			<xs:attributeGroup ref="attlist.kd-grid-toolbar-sub"></xs:attributeGroup>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="attlist.kd-grid-toolbar-sub">
		<xs:attribute name="name" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="create"></xs:enumeration>
					<xs:enumeration value="save"></xs:enumeration>
					<xs:enumeration value="cancel"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="text" type="xs:string"></xs:attribute>
	</xs:attributeGroup>
	<!-- kd-grid-column start by ligeng-->
    <xs:element name="kd-grid-column">
    	<xs:complexType>
    		<xs:attributeGroup ref="attlist.kd-grid-column"></xs:attributeGroup>
    	</xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.kd-grid-column">
    	<xs:attribute name="name" type="xs:string" use="required"/>
    	<xs:attribute name="filterable" type="xs:boolean" />
    	<xs:attribute name="width" type="xs:integer" />
    	<!-- <xs:attribute name="values" type="xs:string"></xs:attribute> -->
    	<xs:attribute name="format" type="xs:string"></xs:attribute>
    	<xs:attribute name="dropDownType">
    		<xs:simpleType>
    			<xs:restriction base="xs:token">
    				<xs:enumeration value="tableDir"></xs:enumeration>
    				<xs:enumeration value="refList"></xs:enumeration>
    				<xs:enumeration value="json"></xs:enumeration>
    			</xs:restriction>
    		</xs:simpleType>
    	</xs:attribute>
    	<xs:attribute name="refenceValue" type="xs:string"></xs:attribute>
    	<xs:attribute name="entity" type="xs:string"></xs:attribute>
    	<xs:attribute name="nameField" type="xs:string"></xs:attribute>
    	<xs:attribute name="valueField" type="xs:string"></xs:attribute>
    	<xs:attribute name="title" type="xs:string"></xs:attribute>
    	<xs:attribute name="conditionJson" type="xs:string" ></xs:attribute>
    	<xs:attribute name="values" type="xs:string" ></xs:attribute>
    	
    	
    </xs:attributeGroup>
    <!-- kd-grid-command start by ligeng-->
    <xs:element name="kd-grid-command">
    	<xs:complexType>
    		<xs:attributeGroup ref="attlist.kd-grid-command"></xs:attributeGroup>
    	</xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.kd-grid-command">
    	<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
    	<xs:attribute name="modelId" type="xs:string" ></xs:attribute>
    	<xs:attribute name="text" type="xs:string" use="required"></xs:attribute>
    	<xs:attribute name="title" type="xs:string"></xs:attribute>
    	<xs:attribute name="width" type="xs:integer"></xs:attribute>
    	<!-- <xs:attribute name="click" type="xs:string"></xs:attribute> -->
    	<xs:attribute name="type" use="required">
    		<xs:simpleType>
    			<xs:restriction base="xs:token">
    				<xs:enumeration value="standard"></xs:enumeration>
    				<xs:enumeration value="server"></xs:enumeration>
    				<xs:enumeration value="client"></xs:enumeration>
    				<xs:enumeration value="click"></xs:enumeration>
    			</xs:restriction>
    		</xs:simpleType>
    	</xs:attribute>
    	<xs:attribute name="url"></xs:attribute>
    	<xs:attribute name="click"></xs:attribute>
    </xs:attributeGroup>
    <!-- kd-grid-field end by ligeng-->
    <xs:element name="kd-grid-field">
    	<xs:complexType>
    		<xs:attributeGroup ref="attlist.kd-grid-field"></xs:attributeGroup>
    	</xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.kd-grid-field">
    	<xs:attribute name="name" type="xs:string" use="required"/>
    	<xs:attribute name="type" type="xs:string" />
    	<xs:attribute name="editable" type="xs:boolean" />
    </xs:attributeGroup>
</xs:schema>

=== ligengwasd/LigengRepository/MyOfbiz/framework/webtools/widget/SecurityManageGrids.xml
<?xml version="1.0" encoding="UTF-8"?>
<grids xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="../../../framework/base/dtd/widget-grid.xsd">
	<kd-grid name="gridUserLogin" selectable="multiple, row" editable="popup">
		<kd-grid-columns>
			<kd-grid-column name="userLoginId" title="登录名"/>
			<kd-grid-column name="currentPassword" title="密码" width="0"/>
			<kd-grid-command name="edit" type="standard" text="修改" title="修改" width="50"/>
			<kd-grid-command type="client" name="edit1" text="查看所属权限组"  title="查看" width="50" url="securityManage" modelId="userLoginId"/>
			<kd-grid-command type="standard" name="destroy" text="删除"  title="删除" width="50"  />
		</kd-grid-columns>
		<kd-grid-toolbar>
			<kd-grid-toolbar-sub name="create" text="添加"/>
			<kd-grid-toolbar-sub name="save" text="保存"/>
			<kd-grid-toolbar-sub name="cancel" text="取消"/>
		</kd-grid-toolbar>
		<kd-grid-datasource gridName="gridUserLogin" entityName="UserLogin" modelId="userLoginId" create="createUserLogin" destroy="deleteUserLogin"  update="updateUserLogin" >
			<kd-grid-field name="userLoginId" type="string"/>
			<kd-grid-field name="userName" type="string" />
			<kd-grid-field name="zSupplierId" type="string" />
			<kd-grid-field name="traceAuth" type="string"/>
			<kd-grid-field name="currentPassword" type="string" />
		</kd-grid-datasource>
	</kd-grid>
	
	<kd-grid name="gridSecurityGroup" selectable="multiple, row" editable="inline">
		<kd-grid-columns>
			<kd-grid-column name="groupId"/>
			<kd-grid-column name="description"/>
			<kd-grid-command name="edit" type="standard" text="修改" title="修改" width="50"/>
			<kd-grid-command type="standard" name="destroy" text="删除"  title="删除" width="50"  />
		</kd-grid-columns>
		<kd-grid-toolbar>
			<kd-grid-toolbar-sub name="create" text="添加"/>
			<kd-grid-toolbar-sub name="save" text="保存"/>
			<kd-grid-toolbar-sub name="cancel" text="取消"/>
		</kd-grid-toolbar>
		<kd-grid-datasource gridName="gridSecurityGroup" entityName="SecurityGroup" modelId="groupId" create="createSecurityGroup" update="updateSecurityGroup" destroy="deleteSecurityGroup">
			<kd-grid-field name="groupId"/>
			<kd-grid-field name="description"/>
		</kd-grid-datasource>
	</kd-grid>
	
	<kd-grid name="gridUserLoginSecurityGroup" selectable="multiple, row" editable="inline">
		<kd-grid-columns>
			<!-- conditionJson="{ 'data':[{'conditionField':'userLoginId','conditionFieldValue':'ligeng'}] }" -->
			<kd-grid-column name="userLoginId" dropDownType="tableDir" entity="UserLogin" nameField="userLoginId" valueField="userLoginId" />
			<kd-grid-column name="groupId" dropDownType="tableDir" entity="SecurityGroup" nameField="description" valueField="groupId"/>
			<kd-grid-command name="editSecurityGroupsss" type="client" text="编辑权限组" title="编辑权限组" width="50" url="findSecurityGroup" modelId="groupId"/>
			<kd-grid-command name="deleteUserLoginSecurityGroup" type="click" text="删除"  title="删除" width="50" click="deleteUserLoginSecurityGroup"/>
		</kd-grid-columns>
		<kd-grid-toolbar>
			<kd-grid-toolbar-sub name="create" text="添加"/>
			<kd-grid-toolbar-sub name="save" text="保存"/>
			<kd-grid-toolbar-sub name="cancel" text="取消"/>
		</kd-grid-toolbar>
		<kd-grid-datasource gridName="gridUserLoginSecurityGroup" entityName="UserLoginSecurityGroup" modelId="userLoginId" create="createUserLoginSecurityGroup" destroy="deleteUserLoginSecurityGroup">
			<kd-grid-field name="userLoginId" editable="true"/>
			<kd-grid-field name="groupId"/>
		</kd-grid-datasource>
	</kd-grid>
	
	<kd-grid name="gridSecurityPermission" selectable="multiple, row" editable="inline">
		<kd-grid-columns>
			<kd-grid-column name="permissionId"/>
			<kd-grid-column name="description"/>
			<kd-grid-command name="edit" type="standard" text="修改" title="修改"  width="50"/>
			<kd-grid-command name="destroy" type="standard" text="删除"  title="删除" width="50" modelId="permissionId"/>
		</kd-grid-columns>
		<kd-grid-toolbar>
			<kd-grid-toolbar-sub name="create" text="添加"/>
			<kd-grid-toolbar-sub name="save" text="保存"/>
			<kd-grid-toolbar-sub name="cancel" text="取消"/>
		</kd-grid-toolbar>
		<kd-grid-datasource gridName="gridSecurityPermission" entityName="SecurityPermission" modelId="permissionId" 
			pageSize="15" create="createSecurityPermission" update="updateSecurityPermission" destroy="deleteSecurityPermission">
			<kd-grid-field name="permissionId"/>
			<kd-grid-field name="description"/>
		</kd-grid-datasource>
	</kd-grid>
	
	<kd-grid name="gridSecurityGroupPermission" selectable="multiple, row" editable="inline">
		<kd-grid-columns>
			<kd-grid-column name="groupId" dropDownType="tableDir" entity="SecurityGroup" nameField="groupId" valueField="groupId"/>
			<kd-grid-column name="permissionId" dropDownType="tableDir" entity="SecurityPermission" nameField="permissionId" valueField="permissionId" />
			<kd-grid-command name="deleteSecurityGroupPermission" type="click" text="删除"  title="删除" width="50" click="deleteSecurityGroupPermission"/>
		</kd-grid-columns>
		<kd-grid-toolbar>
			<kd-grid-toolbar-sub name="create" text="添加"/>
			<kd-grid-toolbar-sub name="save" text="保存"/>
			<kd-grid-toolbar-sub name="cancel" text="取消"/>
		</kd-grid-toolbar>
		<kd-grid-datasource gridName="gridSecurityGroupPermission" entityName="SecurityGroupPermission" modelId="groupId" 
			create="createSecurityGroupPermission" destroy="deleteSecurityGroupPermission">
			<kd-grid-field name="groupId"/>
			<kd-grid-field name="permissionId"/>
		</kd-grid-datasource>
	</kd-grid>
	
</grids>
